name: Build EAP
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ij: [ LATEST-EAP-SNAPSHOT ]
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and verify
        run: ./gradlew clean buildPlugin test verifyPlugin -PpluginIdeaVersion=IC-${{ matrix.ij }} --warning-mode all
