#see https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action
#see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions https://crontab.guru
name: Compatibility EAP
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x.x
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
      - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          ide-versions: |
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
