package lermitage.intellij.battery.status.core;

public enum OshiFeatureName {
    CAPACITY_PERCENT("$CAPACITY_PERCENT"),
    AC("$AC"),
    DISCHARGE_ESTIMATED_TIME("$DISCHARGE_ESTIMATED_TIME"),
    DISCHARGE_ESTIMATED_TIME_LONG("$DISCHARGE_ESTIMATED_TIME_LONG"),
    DISCHARGE_INSTANT_TIME("$DISCHARGE_INSTANT_TIME"),
    DISCHARGE_INSTANT_TIME_LONG("$DISCHARGE_INSTANT_TIME_LONG"),
    CHARGE_ESTIMATED_TIME("$CHARGE_ESTIMATED_TIME"),
    CHARGE_ESTIMATED_TIME_LONG("$CHARGE_ESTIMATED_TIME_LONG"),
    CHARGE_INSTANT_TIME("$CHARGE_INSTANT_TIME"),
    CHARGE_INSTANT_TIME_LONG("$CHARGE_INSTANT_TIME_LONG");

    private final String label;

    OshiFeatureName(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
